#
###################################
# Site wide configuration
####################################
#
title: Haoyu Xu
email: isfrka@gmail.com
description: Haoyu Xu's blog, powered by jekyll.
url: https://xhyzzZ.github.io # the base hostname & protocol for your site
keywords: ["java", "scala", "blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Haoyu Xu
  avatar: avatar.jpg
  job: "Backend Developer"
  bio: "A backend developer who works for Amazon Alexa in Cambridge, Massachusetts."
  email: isfrka@gmail.com
  disqus-shortname: #username
  twitter:  HaoyuXu2
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: xhyzzZ #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: xuhaoyu
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: new_x_h_y
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: kobale
  flickr: #username
  codepen: #username
  telegram: #username
